version: 1
disable_existing_loggers: True

# Define format of output logs (named 'simple').
formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:

    # Create rotating file handler using 'simple' format.
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: ./log/app_logger.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

root:
    level: INFO
    handlers: [console, info_file_handler]
    propogate: yes
